# fly.toml app configuration file generated for arenaroyale on 2026-05-05T19:12:52Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'arenaroyale'
primary_region = 'ams'

[build]

[[services]]
  internal_port = 3000
  protocol = "tcp"
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.ports]]
    handlers = ["http"]
    port = 80

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
